apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  name: {{.Values.applicationName}}-web-application-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-recommender.primary-labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
       app.kubernetes.io/name: ai-recommender-web-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-recommender-web-application
    spec:
      containers:
        - name: ai-recommender-web-application
          image: 'docker.io/psamouelian/ai-recommender:latest'
          ports:
            - containerPort: 8501
              protocol: TCP
          env:
            - name: S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: secret-map
                  key: AWS_S3_ENDPOINT
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: secret-map
                  key: AWS_S3_BUCKET
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: secret-map
                  key: AWS_DEFAULT_REGION
            - name: S3_SKIP_SIGNATURE
              valueFrom:
                configMapKeyRef:
                  name: secret-map
                  key: S3_SKIP_SIGNATURE
            - name: S3_RECOMMENDER_IMAGES_PATH
              valueFrom:
                configMapKeyRef:
                  name: secret-map
                  key: S3_RECOMMENDER_IMAGES_PATH
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: secret-map
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-map
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-map
                  key: DATABASE_NAME
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-map
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-map
                  key: AWS_SECRET_ACCESS_KEY