apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.applicationName}}-secret-map
  namespace: {{.Values.targetNamespace}}
  labels:
    {{- include "ai-recommender.primary-labels" $ | indent 4 }}
type: Opaque
data:
  s3-access-key: bWluaW8=
  s3-secret-key: bWluaW8xMjM=
  database-user: cG9zdGdyZXM=
  database-password: ZWRidGVzdDEyMw==
  database-name: cG9zdGdyZXM=
