apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.applicationName}}-secret-map
  namespace: {{.Values.targetNamespace}}
  labels:
    {{- include "ai-recommender.primary-labels" $ | indent 4 }}
type: Opaque
data:
  database-user: cG9zdGdyZXMK
  database-password: ZWRidGVzdDEyMwo=
  database-name: cG9zdGdyZXMK
