apiVersion: v1
kind: Service
metadata:
  name: {{.Values.applicationName}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-recommender.primary-labels" $ | indent 4 }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 5432-tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: edb-aidb