apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  name: {{.Values.applicationName}}-database-deployment
  namespace: {{.Values.targetNamespace}}
  labels:
    {{- include "ai-recommender.primary-labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
       app.kubernetes.io/name: ai-recommender-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-recommender-database
    spec:
      containers:
        - name: ai-recommender-database
          image: 'docker.io/psamouelian/edb-aidb@sha256:1c398ac0ac7870d5a168cdd88f8e618aa6965f68bb96bb85b33d6436e5379d7a'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.applicationName}}-secret-map
                  key: database-password