apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.applicationName }}-service-account
  labels:
    {{- include "ai-recommender.primary-labels" $ | indent 4 }}
  namespace: {{.Values.targetNamespace}}