apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  name: {{.Values.applicationName}}-web-application-deployment
  namespace: {{.Values.targetNamespace}}
  labels:
    {{- include "ai-recommender.primary-labels" $ | indent 4 }}
spec:
  serviceAccountName: {{.Values.applicationName}}-service-account
  replicas: 1
  selector:
    matchLabels:
       app.kubernetes.io/name: ai-recommender-web-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-recommender-web-application
    spec:
containers:
  - name: ai-recommender-web-application
    image: 'docker.io/psamouelian/edb-aidb@sha256:1c398ac0ac7870d5a168cdd88f8e618aa6965f68bb96bb85b33d6436e5379d7a'
    ports:
      - containerPort: 8501
        protocol: HTTP
    env:
      - name: S3_ENDPOINT_URL
        valueFrom:
          configMapKeyRef:
            name: {{ .Values.applicationName}}-config-map
            key: s3-endpoint-url
      - name: S3_BUCKET_NAME
        valueFrom:
          configMapKeyRef:
            name: {{ .Values.applicationName}}-config-map
            key: s3-bucket-name
      - name: S3_REGION
        valueFrom:
          configMapKeyRef:
            name: {{ .Values.applicationName}}-config-map
            key: s3-region
      - name: S3_SKIP_SIGNATURE
        valueFrom:
          configMapKeyRef:
            name: {{ .Values.applicationName}}-config-map
            key: s3-skip-signature
      - name: S3_RECOMMENDER_IMAGES_PATH
        valueFrom:
          configMapKeyRef:
            name: {{ .Values.applicationName}}-config-map
            key: s3-recommender-images-path
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: {{.Values.applicationName}}-secret-map
            key: database-user
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{.Values.applicationName}}-secret-map
            key: database-password
      - name: DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: {{.Values.applicationName}}-secret-map
            key: database-name
      - name: S3-ACCESS-KEY
        valueFrom:
          secretKeyRef:
            name: {{.Values.applicationName}}-secret-map
            key: s3-access-key
      - name: S3-SECRET-KEY
        valueFrom:
          secretKeyRef:
            name: {{.Values.applicationName}}-secret-map
            key: s3-access-key