apiVersion: v1
kind: Secret
metadata:
  name: inference-secrets
  labels:
    opendatahub.io/dashboard: 'true'
data:
  S3_ENDPOINT_URL: aHR0cHM6Ly9taW5pby1hcGktbWluaW8uYXBwcy5haS1kZXYwMS5rbmkuc3lzZW5nLmRldmNsdXN0ZXIub3BlbnNoaWZ0LmNvbQ==
  S3_BUCKET_NAME: ZWRiLWFpZGI=
  S3_REGION: dXMtZWFzdC0x
  S3_SKIP_SIGNATURE: dHJ1ZQ==
  S3_ACCESS_KEY: bWluaW8=
  S3_SECRET_KEY: bWluaW8xMjM0IQ==
type: Opaque
